version: '3.1'
services:
  notes_api_postgresql:
    build:
      context: docker/databases/NotesApiPostgreSQL
      dockerfile: Dockerfile.NotesApiPostgreSQL
    container_name: notes_api_postgresql_container
    ports:
      - "5433:5432"
    networks:
      - my_network

  notes_api:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.NotesApi
    container_name: notes_api_container
    ports:
      - "8090:8090"
    networks:
      - my_network

networks:
  my_network: